### ISSUE TITLE
동치연산자

### ISSUE THREAD

**Issue by AlvinYou** [zzinpan/Stopwatch.js#1]
https://github.com/zzinpan/Timer/blob/390879c52d01a01543c350052f001cf1c294ed6d/src/Timer.js#L66

동치연산자 쓸때 3개짜리로 바꾸는건 어떨까요?
권장하는것을 쓰는게 더 좋을것 같습니다!    == -> ===

**Comment by zzinpan** [comment]
모두 적용했습니다.
리뷰 감사합니다.
